version: '2'
services:
    leboncoinlistscrapper-app:
        image: fresnault/leboncoinlistscrapper
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017
            - SPRING_DATA_MONGODB_DATABASE=leboncoinListScrapper
            - SPRING_RABBITMQ_HOST=host.docker.internal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application

